apiServerIP: "192.168.48.101"
apiServerPort: "6443"
loxiNodeInfo:
- node: "node1"
  withSmartNIC: "false"
  loxiEndpointIface: "hs1"
  localIP: "192.168.58.101/24"
  endpointIface: "enp0s9"
- node: "node2"
  withSmartNIC: "false"
  loxiEndpointIface: "hs1"
  localIP: "192.168.58.102/24"
  endpointIface: "enp0s9"
- node: "node3"
  withSmartNIC: "false"
  loxiEndpointIface: "hs1"
  localIP: "192.168.58.103/24"
  endpointIface: "enp0s9"
- node: "node4"
  withSmartNIC: "false"
  loxiEndpointIface: "hs1"
  localIP: "192.168.58.104/24"
  endpointIface: "enp0s9"
